/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package developdic;


import javax.swing.DefaultListModel;
import java.io.IOException;
import com.darkprograms.speech.synthesiser.SynthesiserV2;
import com.darkprograms.speech.translator.GoogleTranslate;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.advanced.AdvancedPlayer;


/**
 *
 * @author ADMINISTRATOR
 */
public class GrapHandling extends javax.swing.JFrame {

    DefaultListModel <String> Moutputspelling = new DefaultListModel<>();
    DefaultListModel <String> Moutputexplain = new DefaultListModel<>(); 
    DefaultListModel <String> ListHistory = new DefaultListModel<>(); 
    ListWord L = new ListWord(); 
    ListWord ListHandling = new ListWord(2); 
    Word Wordedit = new Word(); 
    String stringkeySpelling = new String(); 
    int index = -1; 
    int index1 = -1;
    int indexEdit = -1; 
    int flagChangeLanguage = 0; 
  
    String s = String.valueOf(ListHandling.ReturnSizeList()); 

    
    SynthesiserV2 synthesizer = new SynthesiserV2("AIzaSyBOti4mM-6x9WDnZIjIeyEU21OpBXqWBgw");
    /**
     * Creates new form GrapHandling
     */
    public GrapHandling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelOption1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelOptiondefault = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanelHome1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        OutputSpelling = new javax.swing.JList<>();
        buttonadd = new javax.swing.JButton();
        buttondelete = new javax.swing.JButton();
        butEdit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        doispelling = new javax.swing.JTextField();
        doiexplain = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        doingonngu = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Sound = new javax.swing.JLabel();
        textKey = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        SearchVietAnh = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Outputexplain = new javax.swing.JList<>();
        jPanel15 = new javax.swing.JPanel();
        labelSpelling = new javax.swing.JLabel();
        jLabelphienam = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTuDaXoa = new javax.swing.JList<>();
        jPanel17 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        UpDateWords = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GrapHandling ");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/abc.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MY DICTIONARY");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("education");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jPanelOption1.setBackground(new java.awt.Color(0, 51, 204));
        jPanelOption1.setToolTipText("");
        jPanelOption1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelOption1MousePressed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Home ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Home_Page_35px.png"))); // NOI18N

        javax.swing.GroupLayout jPanelOption1Layout = new javax.swing.GroupLayout(jPanelOption1);
        jPanelOption1.setLayout(jPanelOption1Layout);
        jPanelOption1Layout.setHorizontalGroup(
            jPanelOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOption1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelOption1Layout.setVerticalGroup(
            jPanelOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelOption1Layout.createSequentialGroup()
                .addGroup(jPanelOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelOption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 40));

        jPanelOptiondefault.setBackground(new java.awt.Color(0, 0, 153));
        jPanelOptiondefault.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelOptiondefaultMousePressed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("History");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Historical_35px.png"))); // NOI18N

        javax.swing.GroupLayout jPanelOptiondefaultLayout = new javax.swing.GroupLayout(jPanelOptiondefault);
        jPanelOptiondefault.setLayout(jPanelOptiondefaultLayout);
        jPanelOptiondefaultLayout.setHorizontalGroup(
            jPanelOptiondefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptiondefaultLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanelOptiondefaultLayout.setVerticalGroup(
            jPanelOptiondefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelOptiondefaultLayout.createSequentialGroup()
                .addGroup(jPanelOptiondefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOptiondefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelOptiondefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 40));

        jPanel6.setBackground(new java.awt.Color(0, 0, 153));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Info");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Info_35px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 420));

        jPanel3.setBackground(new java.awt.Color(254, 253, 253));
        jPanel3.setForeground(new java.awt.Color(0, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new java.awt.CardLayout());

        jPanelHome1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBorder(null);

        OutputSpelling.setForeground(new java.awt.Color(0, 0, 153));
        OutputSpelling.setToolTipText("");
        OutputSpelling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OutputSpellingMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(OutputSpelling);

        jPanelHome1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 220, 250));

        buttonadd.setBackground(new java.awt.Color(0, 0, 153));
        buttonadd.setForeground(new java.awt.Color(255, 255, 255));
        buttonadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Add_File_40px.png"))); // NOI18N
        buttonadd.setBorder(null);
        buttonadd.setBorderPainted(false);
        buttonadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonaddMouseClicked(evt);
            }
        });
        jPanelHome1.add(buttonadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 40, 50));

        buttondelete.setBackground(new java.awt.Color(0, 0, 153));
        buttondelete.setForeground(new java.awt.Color(0, 51, 255));
        buttondelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_File_40px.png"))); // NOI18N
        buttondelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttondeleteMouseClicked(evt);
            }
        });
        jPanelHome1.add(buttondelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 40, 50));

        butEdit.setBackground(new java.awt.Color(0, 0, 153));
        butEdit.setForeground(new java.awt.Color(0, 51, 255));
        butEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Edit_File_40px_1.png"))); // NOI18N
        butEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butEditMouseClicked(evt);
            }
        });
        jPanelHome1.add(butEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 40, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Sửa Từ & Thêm Từ ");
        jPanelHome1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 190, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jSeparator1.setOpaque(true);
        jPanelHome1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 220, 4));

        doispelling.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        doispelling.setForeground(new java.awt.Color(0, 0, 153));
        doispelling.setText("Spelling...");
        doispelling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doispellingMouseClicked(evt);
            }
        });
        doispelling.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                doispellingKeyReleased(evt);
            }
        });
        jPanelHome1.add(doispelling, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 220, 30));

        doiexplain.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        doiexplain.setForeground(new java.awt.Color(0, 0, 153));
        doiexplain.setText("Explain...");
        doiexplain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doiexplainMouseClicked(evt);
            }
        });
        doiexplain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                doiexplainKeyReleased(evt);
            }
        });
        jPanelHome1.add(doiexplain, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 220, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator2.setOpaque(true);
        jPanelHome1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 220, 4));

        doingonngu.setBackground(new java.awt.Color(255, 255, 255));
        doingonngu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sort.png"))); // NOI18N
        doingonngu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doingonnguMouseClicked(evt);
            }
        });
        jPanelHome1.add(doingonngu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 30));

        jPanel9.setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));

        Sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Speaker_25px.png"))); // NOI18N
        Sound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoundMouseClicked(evt);
            }
        });

        textKey.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textKey.setForeground(new java.awt.Color(0, 0, 153));
        textKey.setText("Search...");
        textKey.setToolTipText("");
        textKey.setBorder(null);
        textKey.setSelectionColor(new java.awt.Color(255, 255, 255));
        textKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textKeyMouseClicked(evt);
            }
        });
        textKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textKeyKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textKey, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sound, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sound, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textKey, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel4, "card2");

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchVietAnh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        SearchVietAnh.setForeground(new java.awt.Color(0, 0, 153));
        SearchVietAnh.setText("Tìm Kiếm...");
        SearchVietAnh.setBorder(null);
        SearchVietAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchVietAnhMouseClicked(evt);
            }
        });
        SearchVietAnh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchVietAnhKeyReleased(evt);
            }
        });
        jPanel14.add(SearchVietAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 190, 30));

        jPanel9.add(jPanel14, "card3");

        jPanelHome1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 40));

        jPanel11.setLayout(new java.awt.CardLayout());

        jScrollPane1.setBorder(null);

        Outputexplain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        Outputexplain.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Outputexplain.setForeground(new java.awt.Color(0, 0, 153));
        Outputexplain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OutputexplainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Outputexplain);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel11.add(jPanel12, "card2");

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSpelling.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelSpelling.setForeground(new java.awt.Color(0, 0, 153));
        labelSpelling.setText("Search...");
        jPanel15.add(labelSpelling, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 40));

        jPanel11.add(jPanel15, "card3");

        jPanelHome1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 230, 40));

        jLabelphienam.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelphienam.setForeground(new java.awt.Color(0, 0, 153));
        jPanelHome1.add(jLabelphienam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 220, 30));

        jPanel5.add(jPanelHome1, "card2");

        jPanel7.setBackground(new java.awt.Color(0, 0, 153));

        jLabel4.setBackground(new java.awt.Color(0, 0, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Các từ đã xóa. ");

        jScrollPane2.setViewportView(jListTuDaXoa);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel7, "card3");

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setForeground(new java.awt.Color(0, 0, 153));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Cảm ơn bạn đã sử dụng MY DICTIONARY ^_^");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Chế độ hiển thị thông tin từ tiếng anh. Bạn click vào nghĩa tiếng anh 1 lần.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("Chế độ nghe. Bạn click vào nghĩa cần nghe 2 lần. ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("+) Để thêm từ.  ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("Cách 1: bạn click vào ô Spelling... để thêm tiếng anh và click vào ô Explain... thêm tiếng việt");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 153));
        jLabel18.setText("-> click vào nút thêm.");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 153));
        jLabel19.setText("Cách 2: bạn click vào ô nghĩa tiếng Việt -> click vào nút thêm.");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("+) Để xóa từ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setText("Bạn click vào nghĩa tiếng anh tìm được cần xóa dưới ô Search -> click vào nút xóa. ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 153));
        jLabel22.setText("+) Để sửa từ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 153));
        jLabel23.setText("Bạn click vào nghĩa tiếng anh tìm được cần sửa -> click vào ô Spelling... để sửa nghĩa TA");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 153));
        jLabel24.setText("click vào ô Explain... để sửa tiếng việt -> click vào kí tự sửa. ");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jPanel5.add(jPanel17, "card4");

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 580, 350));

        UpDateWords.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UpDateWords.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(UpDateWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 690, 400));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator3.setOpaque(true);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 450, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OutputSpellingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutputSpellingMouseClicked
        // TODO add your handling code here:
        index = OutputSpelling.getSelectedIndex();
        indexEdit = OutputSpelling.getSelectedIndex();
        String spelling = stringkeySpelling;  
        if (evt.getClickCount() == 1 && L.ReturnSizeList() > 0 && index != -1){
            Moutputexplain.clear();
            Moutputexplain.addElement(L.ReturnWordExplain(index));
            Outputexplain.setModel(Moutputexplain);
            doispelling.setText(L.ReturnWordSpelling(index));
            doiexplain.setText(L.ReturnWordExplain(index));
            jLabelphienam.setText(L.ReturnWordPhienAm(index));
            index = -1; 
        }
        if (evt.getClickCount() == 2 && L.ReturnSizeList() > 0 && index != -1){ 
            speak(L.ReturnWordSpelling(index));   
            index = -1; 
        }
    }//GEN-LAST:event_OutputSpellingMouseClicked
 
    private void OutputexplainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutputexplainMouseClicked
        // TODO add your handling code here:
        index1 = Outputexplain.getSelectedIndex(); 
        if (evt.getClickCount() == 2){
            if (index1 != -1){
                speak(Outputexplain.getSelectedValue());
            }
            else {
                speak(L.ReturnWordExplain(index));  
            }
        }
    }//GEN-LAST:event_OutputexplainMouseClicked

    private void buttonaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonaddMouseClicked
        // TODO add your handling code here:
        String Spelling = new String(); 
        String explain = new String(); 
        Dictionary1 Dicdelete = new Dictionary1(); 
        if ((!stringkeySpelling.equals("Search...") && !stringkeySpelling.equals("")) && Outputexplain.getSelectedIndex() == 0){
            Spelling = stringkeySpelling; 
            explain = Outputexplain.getSelectedValue();
        }
        else {
            Spelling = doispelling.getText(); 
            explain = doiexplain.getText();
        }
        int check = Dicdelete.BinarySearch(Spelling);
       
        if (check == -1){
            if ((!Spelling.equals("Spelling...") && !Spelling.equals("")) && (!explain.equals("Explain...") && !explain.equals("")) ){
           
            int k = JOptionPane.showConfirmDialog(rootPane, "Bạn muốn thêm từ này ?", "Dictionary", 0); 
            
            if (k == 0){
                
                Word W = new Word(); 
                
                W.setSpelling(Spelling); 
                
                W.setExplain(explain);
                
                W.setphienam("");
                
                ListHandling.AddWordToList(W);
                ListHandling.Sort();
                ListHandling.WriteListToFile();
                String s = String.valueOf(ListHandling.ReturnSizeList()); 
                UpDateWords.setText("Words" + ": " + s);
            }
            doispelling.setText("Spelling...");
            doiexplain.setText("Explain...");
            }else {
                doispelling.setText("Spelling...");
                doiexplain.setText("Explain...");
            }
        }else {  
            JOptionPane.showMessageDialog(rootPane, "Từ đã có trong từ điển !", "MyDictionary", HEIGHT);
        } 
    }//GEN-LAST:event_buttonaddMouseClicked

    private void buttondeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttondeleteMouseClicked
        // TODO add your handling code here:
        String s1 = OutputSpelling.getSelectedValue(); 
        
        if (s1 != null && evt.getClickCount() == 1){
            int check = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn xóa ?", "Dictionary", 0);
            if (check == 0){
                Dictionary1 D = new Dictionary1(); 
            
                System.out.println(D.ReturnSpellingInList(s1));
                ListHistory.addElement("Spelling: " + s1 + "                        " + "Explain: " + Moutputexplain.get(0));
                ListHandling.DeleteWordToList(s1);
                ListHandling.WriteListToFile();
                JOptionPane.showMessageDialog(rootPane, "Xóa từ thành công");
                String s = String.valueOf(ListHandling.ReturnSizeList()); 
                UpDateWords.setText("Words" + ": " + s);
            }       
        }
    }//GEN-LAST:event_buttondeleteMouseClicked

    private void SoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoundMouseClicked
        // TODO add your handling code here:
        String S = stringkeySpelling;
        if (!S.equals("") && evt.getClickCount() == 1){
            speak(S); 
        }
    }//GEN-LAST:event_SoundMouseClicked

    private void textKeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textKeyKeyReleased
        // TODO add your handling code here:
        Dictionary1 Dic = new Dictionary1();
        stringkeySpelling = textKey.getText();

        Moutputspelling.clear();

        L = Dic.SearchKeyWord(stringkeySpelling);

        if (!stringkeySpelling.equals("") && L.ReturnSizeList() > 0){

            for (int i = 0; i < L.ReturnSizeList(); i++){

                Moutputspelling.addElement(L.ReturnWordSpelling(i));

            }

            OutputSpelling.setModel(Moutputspelling);

        }
        else if (!stringkeySpelling.equals("") && L.ReturnSizeList() == 0){
            String s2 = TranslateGoogle("vi", stringkeySpelling);
            Moutputexplain.clear();
            Moutputexplain.addElement(s2);
            Outputexplain.setModel(Moutputexplain);
        }
        if (stringkeySpelling.equals("")){
            Moutputexplain.clear();
        }
    }//GEN-LAST:event_textKeyKeyReleased

    private void jPanelOption1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelOption1MousePressed
        // TODO add your handling code here:
        setColor(jPanelOption1,0,51,204); 
        resetColor(jPanelOptiondefault, 0,0,153);
        resetColor(jPanel6, 0,0,153);
        // reset panel viền. [255,255,255], [0,0,153]
        setColor(jPanel8, 255, 255, 255); 
        resetColor(jPanel10, 0,0,153);
        resetColor(jPanel13, 0,0,153);
        // chuyen doi che do 1
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        jPanel5.add(jPanelHome1); 
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jPanelOption1MousePressed

    private void jPanelOptiondefaultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelOptiondefaultMousePressed
        // TODO add your handling code here:
        setColor(jPanelOptiondefault,0,51,204); 
        resetColor(jPanelOption1, 0,0,153);
        resetColor(jPanel6, 0,0,153);
        // reset panel viền. 
        setColor(jPanel10, 255, 255, 255); 
        resetColor(jPanel8, 0,0,153);
        resetColor(jPanel13, 0,0,153);
        // chuyen doi che do 2. 
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        jPanel5.add(jPanel7); 
        jPanel5.repaint();
        jPanel5.revalidate();
        jListTuDaXoa.setModel(ListHistory);
    }//GEN-LAST:event_jPanelOptiondefaultMousePressed

    private void doispellingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doispellingMouseClicked
        // TODO add your handling code here:
        doispelling.setText("");
    }//GEN-LAST:event_doispellingMouseClicked

    private void doiexplainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doiexplainMouseClicked
        // TODO add your handling code here:
        doiexplain.setText("");    
    }//GEN-LAST:event_doiexplainMouseClicked

    private void doispellingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doispellingKeyReleased
        // TODO add your handling code here:
        String s = new String(); 
        
        s = doispelling.getText(); 
        if (!s.equals("")){
            Wordedit.setSpelling(s);
        }
    }//GEN-LAST:event_doispellingKeyReleased

    private void doiexplainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doiexplainKeyReleased
        // TODO add your handling code here:
        String s = new String(); 
        
        s = doiexplain.getText();
        if (!s.equals("")){
            Wordedit.setExplain(s);
        }
    }//GEN-LAST:event_doiexplainKeyReleased

    private void butEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butEditMouseClicked
        // TODO add your handling code here:
        String s1 = new String(); 
        String s2 = new String(); 
        Word W = new Word(); 
        Dictionary1 D = new Dictionary1();
        s1 = doispelling.getText(); 
        s2 = doiexplain.getText();       
    
        if (OutputSpelling.getSelectedIndex() != -1 && !s1.equals("Spelling...") && !s2.equals("Explain...") && !s1.equals("") && !s2.equals("") && indexEdit != -1){          
            int IC = D.BinarySearch(L.ReturnWordSpelling(indexEdit)); 
            W.setSpelling(s1);
            W.setExplain(s2);

            W.setphienam(ListHandling.ReturnWordPhienAm(IC));
            ListHandling.ChangeWord(W, IC);
            ListHandling.WriteListToFile();
            doispelling.setText("Spelling...");
            doiexplain.setText("Explain...");
            indexEdit = -1; 
            JOptionPane.showMessageDialog(rootPane, "Từ đã được sửa.^_^.");
        }
        else if (OutputSpelling.getSelectedIndex() == -1 && !s1.equals("Spelling...") && !s2.equals("Explain...") && !s1.equals("") && !s2.equals("")){
         
            int IC = D.BinarySearch(s1); 
            if (IC != -1){
                W.setSpelling(s1);
                W.setExplain(s2); 
                W.setphienam(ListHandling.ReturnWordPhienAm(IC));
                ListHandling.ChangeWord(W, IC);
                ListHandling.WriteListToFile();
                doispelling.setText("Spelling...");
                doiexplain.setText("Explain...");
            }else {
                JOptionPane.showMessageDialog(rootPane, "Từ này không có trong từ điển !");
                doispelling.setText("Spelling...");
                doiexplain.setText("Explain...");
            }
        }
        else {
            doispelling.setText("Spelling...");
            doiexplain.setText("Explain...");
        }

    }//GEN-LAST:event_butEditMouseClicked

    private void textKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textKeyMouseClicked
        // TODO add your handling code here:
        String s = String.valueOf(ListHandling.ReturnSizeList()); 
        UpDateWords.setText("Words" + ": " + s);
        textKey.setText("");
    }//GEN-LAST:event_textKeyMouseClicked

    private void SearchVietAnhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchVietAnhKeyReleased
        // TODO add your handling code here:

          String s = SearchVietAnh.getText();

          Dictionary1 D = new Dictionary1(); 
          if (!s.equals("")){
              String s1 = D.ReturnSpellingInList(s); 

              if (!s1.equals("")){
                  labelSpelling.setText(s1);
                  System.out.println(s1);
                  doispelling.setText(s1);
                  doiexplain.setText(s);
                  jLabelphienam.setText(D.ReturnPhienAMInList(s1));
              }
              else {
                  String s2 = TranslateGoogle("en", s); 
                  if (s2 != null){
                      labelSpelling.setText(s2);
                  }
                  else {
                      labelSpelling.setText("");
                  }
              }
          }
    }//GEN-LAST:event_SearchVietAnhKeyReleased

    private void doingonnguMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doingonnguMouseClicked
        // TODO add your handling code here:
        if (flagChangeLanguage == 0){
            jPanel9.removeAll();
            jPanel9.repaint();
            jPanel9.revalidate();
            jPanel9.add(jPanel14); 
            jPanel9.repaint();
            jPanel9.revalidate();
            // chuyen phan dich. 
            jPanel11.removeAll();
            jPanel11.repaint();
            jPanel11.revalidate();
            jPanel11.add(jPanel15); 
            jPanel11.repaint();
            jPanel11.revalidate();
            flagChangeLanguage = 1; 
        }
        else {
            jPanel9.removeAll();
            jPanel9.repaint();
            jPanel9.revalidate();
            jPanel9.add(jPanel4); 
            jPanel9.repaint();
            jPanel9.revalidate();
            // chuyen phan dich. 
            jPanel11.removeAll();
            jPanel11.repaint();
            jPanel11.revalidate();
            jPanel11.add(jPanel12); 
            jPanel11.repaint();
            jPanel11.revalidate();
            flagChangeLanguage = 0; 
        }
        textKey.setText("Search...");
        SearchVietAnh.setText("Tìm Kiếm...");
        labelSpelling.setText("Search...");
        Moutputspelling.clear();
        Moutputexplain.clear();
        doispelling.setText("Spelling...");
        doiexplain.setText("Explain...");
        jLabelphienam.setText("");
    }//GEN-LAST:event_doingonnguMouseClicked

    private void SearchVietAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchVietAnhMouseClicked
        // TODO add your handling code here:
        SearchVietAnh.setText("");
    }//GEN-LAST:event_SearchVietAnhMouseClicked

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
        setColor(jPanel6,0,51,204); 
        resetColor(jPanelOptiondefault, 0,0,153);
        resetColor(jPanelOption1, 0,0,153);
        // reset panel viền. 
        setColor(jPanel13, 255, 255, 255); 
        resetColor(jPanel10, 0,0,153);
        resetColor(jPanel8, 0,0,153);
        // chuyen doi che do 2. 
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        jPanel5.add(jPanel17); 
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jPanel6MousePressed
    // speak hadling. 
    
    public void speak(String text) {

            Thread thread = new Thread(() -> {
                try {
                    synthesizer.setSpeed(0.9);
                    AdvancedPlayer player = new AdvancedPlayer(synthesizer.getMP3Data(text));
                    player.play();
                } catch (IOException | JavaLayerException e) {

//                    e.printStackTrace();
                      System.out.println("Không có Internet!!!");
                    
                }
            });
            thread.setDaemon(false);
            thread.start();    
    // translate hadling. 
    }
    
    String TranslateGoogle(String tagetlanguage, String s){
        String s1 = ""; 
        try{
            s1 = GoogleTranslate.translate(tagetlanguage, s); 
        }catch(IOException e){
//            System.out.println(e.getLocalizedMessage());
              System.out.println("Not Internet !!!");
        }
        if (!s1.equals("")){
            return s1; 
        }
        else {
            return "Không kết nối"; 
        }
    }
    
    private void setColor(JPanel pane, int m1, int m2, int m3){
        pane.setBackground(new Color(m1, m2, m3));
    }
    
    private void resetColor(JPanel pane, int m1, int m2, int m3){
        pane.setBackground(new Color(m1, m2, m3));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrapHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrapHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrapHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrapHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrapHandling().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> OutputSpelling;
    private javax.swing.JList<String> Outputexplain;
    private javax.swing.JTextField SearchVietAnh;
    private javax.swing.JLabel Sound;
    private javax.swing.JLabel UpDateWords;
    private javax.swing.JButton butEdit;
    private javax.swing.JButton buttonadd;
    private javax.swing.JButton buttondelete;
    private javax.swing.JTextField doiexplain;
    private javax.swing.JButton doingonngu;
    private javax.swing.JTextField doispelling;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelphienam;
    private javax.swing.JList<String> jListTuDaXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelHome1;
    private javax.swing.JPanel jPanelOption1;
    private javax.swing.JPanel jPanelOptiondefault;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelSpelling;
    private javax.swing.JTextField textKey;
    // End of variables declaration//GEN-END:variables
}
